spring.application.name=api-gateway
server.port=8080

### KEYCLOAK
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/auth-realm

### AGENDAMENTO-SERVICE
spring.cloud.gateway.routes[0].id=agendamento-service
spring.cloud.gateway.routes[0].uri=http://agendamento-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/agendamento/**

### CLINICA-SERVICE
spring.cloud.gateway.routes[1].id=clinica-service
spring.cloud.gateway.routes[1].uri=http://clinica-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/clinica/**

### PROCEDIMENTO-SERVICE
spring.cloud.gateway.routes[2].id=procedimento-service
spring.cloud.gateway.routes[2].uri=http://procedimento-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/procedimento/**