spring.application.name=clinica-service
server.port=8082

# security config
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/auth-realm/protocol/openid-connect/certs

#rabbitmq config
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Database config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql-clinica:3306/db_clinica
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.error.include-exception=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web=DEBUG